### PR TITLE
Design branch

### PR DESCRIPTION
**Pull request by RoodzFernando**
This our responsive design project submit for reviews!

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
### Hello team  🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. There should be a main and a sub-navigation bar on large screen, and they should collapse to a hamburger menu icon on small screens.

2. You should have 3 breakpoints: Large screen size, Medium screen size, and small screen size.

3. Fix the linter errors on your project, find out more on how to do that in [here](https://github.com/microverseinc/linters-config/tree/master/css)

4. The **Latest funding rounds on Index** section is getting on top of the navbar when you scroll down fix that.

5. Remove the borders on **the latest news** section elements.

6. The project is not responsive, work on the CSS and make it look like the original website then submit a new code review request.

### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

**Comment by RoodzFernando** [comment]
We tried the above-provided solution in regards to Stickler, and it seems not to be working in our case!

**Review by Redvanisation — CHANGES_REQUESTED** [review]
### Hello team  🌟

**Good so far, but we still have to work on some more improvements before moving on ⬇️** 

1. For the large screen sizes the Logo should appear on the first article image, then goes in the top left corner of the page on the medium screen sizes and less, like on the original website, please fix that.

2. You should have 3 breakpoints: Large screen size, Medium screen size, and small screen size as required in the previous review, please implement that.

3. The **Latest funding rounds on Index** is not responsive on 769px screen sizes and above, implement the required media queries and fix that.

4. The CSS linting errors should be fixed for the project to be approved.

### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

**Comment by RoodzFernando** [comment]
We have fixed all of the problems except for setting stickler properly "Error: ENOENT: no such file or directory, open '/src/src/‘stylelint.config.js’' Please help us we can't figure out the problem.

**Comment by christianotieno** [comment]
Our code has passed all the requirements and tests requirements. We now invite reviews.

**Review by wathigo — APPROVED** [review]
### Hi @RoodzFernando  and @ChristianOtieno  :wave:  
Great work on the project!

**This is approved!**

_Happy Coding :computer: 
Reviewed by: **Simon Wathigo**_

**Pull request merged**
